# Generated by Django 3.2.3 on 2021-06-27 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('Autor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Autor')),
                ('nombreAutor', models.CharField(max_length=100, verbose_name='Nombre Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('noticia_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Noticia')),
                ('cuerpo', models.CharField(max_length=1000, verbose_name='Cuerpo Noticia')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='images')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
