# Generated by Django 3.2.3 on 2021-06-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='cuerpo',
            field=models.TextField(max_length=1000, verbose_name='Cuerpo Noticia'),
        ),
    ]
